/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123570-gf72f692afa-20260320"
#endif /* AVUTIL_FFVERSION_H */
