#pragma once
// Driver build version: the git commit count at compile time.
//
// Regenerated by scripts/compile-driver.ps1 (and CI) from
// `git rev-list --count HEAD` before every build, so the running driver
// always reports the commit it was built from. The fallback below ("dev")
// is only used when the header was never generated (e.g. a source export
// without the script); never edit this file by hand.
#define DRIVER_BUILD_VERSION "114"

