# Bakes the git commit count into DriverVersion.h so the running driver
# reports its build in "BRIDGE_ACK v1 <count>". Called by compile-driver.ps1
# and CI, so local and runner builds stamp the identical header. An explicit
# -Count wins (release workflow); otherwise git rev-list --count HEAD, or
# "dev" when git is unavailable. Never edit DriverVersion.h by hand.
param([string]$Count = "")
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$version = "dev"
if ($Count) {
    $version = $Count.Trim()
} else {
    try { $c = (git -C $root rev-list --count HEAD 2>$null); if ($c -and $LASTEXITCODE -eq 0) { $version = "$c".Trim() } } catch {}
}
$versionHeader = "$root\driver_cardboardplusplus\include\DriverVersion.h"
Set-Content -LiteralPath $versionHeader -Value ('#pragma once
// Driver build version: the git commit count at compile time.
//
// Regenerated by scripts/bake-driver-version.ps1 (via
// scripts/compile-driver.ps1 or CI) from `git rev-list --count HEAD`
// before every build, so the running driver always reports the commit it
// was built from. The fallback below ("dev") is only used when the header
// was never generated (e.g. a source export without the script); never
// edit this file by hand.
#define DRIVER_BUILD_VERSION "' + $version + '"
')
Write-Host "Driver version: $version" -ForegroundColor Cyan
