# bake-driver-version.ps1 - Bake the git commit count into
# driver_cardboardplusplus/include/DriverVersion.h so the running driver
# reports which commit it was built from ("BRIDGE_ACK v1 <count>").
#
# Single source of truth for the bake: scripts/compile-driver.ps1 and CI
# (.github/workflows/build-driver.yml, release.yml) all call this script,
# so local and runner builds stamp the identical header. Never edit
# DriverVersion.h by hand.
#
# An explicit count (e.g. the release workflow's version job) wins when
# given; otherwise the count comes from `git rev-list --count HEAD`.
param([string]$Count = "")
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot

# Falls back to "dev" when git is unavailable (e.g. source export).
# NOTE: the local is $version on purpose - PowerShell variables are
# case-insensitive, so $count would clobber the $Count parameter.
$version = "dev"
if ($Count) {
    $version = $Count.Trim()
} else {
    try { $c = (git -C $root rev-list --count HEAD 2>$null); if ($c -and $LASTEXITCODE -eq 0) { $version = "$c".Trim() } } catch {}
}
$versionHeader = "$root\driver_cardboardplusplus\include\DriverVersion.h"
Set-Content -LiteralPath $versionHeader -Value ('#pragma once
// Driver build version: the git commit count at compile time.
//
// Regenerated by scripts/bake-driver-version.ps1 (via
// scripts/compile-driver.ps1 or CI) from `git rev-list --count HEAD`
// before every build, so the running driver always reports the commit it
// was built from. The fallback below ("dev") is only used when the header
// was never generated (e.g. a source export without the script); never
// edit this file by hand.
#define DRIVER_BUILD_VERSION "' + $version + '"
')
Write-Host "Driver version: $version" -ForegroundColor Cyan
