# compile-driver.ps1 — Build the SteamVR driver DLL
param([string]$Configuration = "Release")
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$sln = "$root\driver_cardboardplusplus\driver_cardboardplusplus.sln"

# The driver links the pinned FFmpeg majors — fetch the runtime DLLs from
# GitHub when missing, then validate the vendored tree matches deps.json
# before paying for a build that can't run.
. "$PSScriptRoot\ffmpeg-deps.ps1"
Ensure-FfmpegDeps "$root\driver_cardboardplusplus\lib\ffmpeg"

# Bake the git commit count into include/DriverVersion.h so the running
# driver reports which commit it was built from ("BRIDGE_ACK v1 <count>").
# Falls back to "dev" when git is unavailable (e.g. source export).
$count = "dev"
try { $c = (git -C $root rev-list --count HEAD 2>$null); if ($c) { $count = $c.Trim() } } catch {}
$versionHeader = "$root\driver_cardboardplusplus\include\DriverVersion.h"
Set-Content -LiteralPath $versionHeader -Value ('#pragma once
// Driver build version: the git commit count at compile time.
//
// Regenerated by scripts/compile-driver.ps1 (and CI) from
// `git rev-list --count HEAD` before every build, so the running driver
// always reports the commit it was built from. The fallback below ("dev")
// is only used when the header was never generated (e.g. a source export
// without the script); never edit this file by hand.
#define DRIVER_BUILD_VERSION "' + $count + '"
')
Write-Host "Driver version: $count" -ForegroundColor Cyan

$vsWhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vsWhere)) { throw "vswhere.exe not found - install Visual Studio" }
$msbuild = & $vsWhere -latest -requires Microsoft.Component.MSBuild -find "MSBuild\**\Bin\amd64\MSBuild.exe" | Select-Object -First 1
if (-not $msbuild) { throw "MSBuild not found - install the C++ build tools in Visual Studio" }

Write-Host "Building driver ($Configuration|x64)..." -ForegroundColor Cyan
& $msbuild $sln /p:Configuration=$Configuration /p:Platform=x64 /v:minimal
if ($LASTEXITCODE -ne 0) { throw "driver build failed" }
Write-Host "Driver built: driver_cardboardplusplus\x64\$Configuration\driver_cardboardplusplus.dll" -ForegroundColor Green
