name: Build Driver

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'driver_cardboardplusplus/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'driver_cardboardplusplus/**'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Driver
      run: msbuild driver_cardboardplusplus\driver_cardboardplusplus.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=x64
